server:
  port: 8000

spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active:
      - server
      - register
      - monitor
      - redis
      - feign
  main:
    #    bean 定义覆盖
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
