server:
  port: 8000

spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active:
      - server
      - register
      - monitor
      - redis
      - feign
  thymeleaf:
    enabled: true
    mode: HTML
    cache: false
    encoding: utf-8
    suffix: .html
    servlet:
      content-type: text/html
  main:
    # bean 定义覆盖
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      # 不启动网关
      # enabled: false
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # auth
        - id: auth_route
          uri: lb://iot-center-auth
          predicates:
            - Path=/api/v3/auth/user/**,/api/v3/auth/black_ip/**,/api/v3/auth/tenant/**,/api/v3/auth/dictionary/**
          filters:
            - StripPrefix=2
            - Authenticator
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # manager
        - id: manager_route
          uri: lb://iot-center-manager
          predicates:
            - Path=/api/v3/manager/**
          filters:
            - StripPrefix=2
            - Authenticator
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # data
        - id: data_route
          uri: lb://iot-center-data
          predicates:
            - Path=/api/v3/data/**
          filters:
            - StripPrefix=2
            #- Authenticator
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # rtmp
        - id: rtmp_route
          uri: lb://dc3-transfer-rtmp
          predicates:
            - Path=/api/v3/rtmp/**
          filters:
            - StripPrefix=2
            - Authenticator
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: default
                fallbackUri: 'forward:/fallback'
  redis:
    database: 0

logging:
  level:
    # 日志等级
    org.industry: debug