spring:
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:admin}
eureka:
  instance:
    hostname: '@project.artifactId@'
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
  #    没有配置的情况下有问题
  #    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    region: iot
    availability-zones:
      iot: defaultZone
    prefer-same-zone-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${EUREKA_HOST:iot-center-register}:${EUREKA_PORT:8100}/eureka
#      todo fix bug 开启自我注册，控制台报错
#      获取服务元信息
#    fetch-registry: false
#      自己注册自己
#    register-with-eureka: false