spring:
  rabbitmq:
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:iot}
    host: ${RABBITMQ_HOST:iot-rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true