spring:
  redis:
    host: ${REDIS_HOST:iot-redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:admin@123}
    timeout: 15S
    lettuce:
      pool:
        max-active: 64
        min-idle: 4
  # @caching @cacheable的实现类型，type = redis
  cache:
    type: redis
    cache-names: iot-cache