driver:
  tenant: default

spring:
  application:
    name: ${driver.project}_${driver.tenant}
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false