spring:
  rabbitmq:
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:dc3}
    host: ${RABBITMQ_HOST:dc3-rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:dc3}
    password: ${RABBITMQ_PASSWORD:dc3}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true